// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/email/proto/email.proto

package emailpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendActivationEmailRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Email           string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ActivationToken string                 `protobuf:"bytes,2,opt,name=activation_token,json=activationToken,proto3" json:"activation_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendActivationEmailRequest) Reset() {
	*x = SendActivationEmailRequest{}
	mi := &file_internal_email_proto_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActivationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActivationEmailRequest) ProtoMessage() {}

func (x *SendActivationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_email_proto_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActivationEmailRequest.ProtoReflect.Descriptor instead.
func (*SendActivationEmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_email_proto_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendActivationEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendActivationEmailRequest) GetActivationToken() string {
	if x != nil {
		return x.ActivationToken
	}
	return ""
}

type SendActivationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActivationEmailResponse) Reset() {
	*x = SendActivationEmailResponse{}
	mi := &file_internal_email_proto_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActivationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActivationEmailResponse) ProtoMessage() {}

func (x *SendActivationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_email_proto_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActivationEmailResponse.ProtoReflect.Descriptor instead.
func (*SendActivationEmailResponse) Descriptor() ([]byte, []int) {
	return file_internal_email_proto_email_proto_rawDescGZIP(), []int{1}
}

func (x *SendActivationEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_email_proto_email_proto protoreflect.FileDescriptor

const file_internal_email_proto_email_proto_rawDesc = "" +
	"\n" +
	" internal/email/proto/email.proto\x12\x05email\"]\n" +
	"\x1aSendActivationEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12)\n" +
	"\x10activation_token\x18\x02 \x01(\tR\x0factivationToken\"7\n" +
	"\x1bSendActivationEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2l\n" +
	"\fEmailService\x12\\\n" +
	"\x13SendActivationEmail\x12!.email.SendActivationEmailRequest\x1a\".email.SendActivationEmailResponseB\x1eZ\x1cinternal/email/proto/emailpbb\x06proto3"

var (
	file_internal_email_proto_email_proto_rawDescOnce sync.Once
	file_internal_email_proto_email_proto_rawDescData []byte
)

func file_internal_email_proto_email_proto_rawDescGZIP() []byte {
	file_internal_email_proto_email_proto_rawDescOnce.Do(func() {
		file_internal_email_proto_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_email_proto_email_proto_rawDesc), len(file_internal_email_proto_email_proto_rawDesc)))
	})
	return file_internal_email_proto_email_proto_rawDescData
}

var file_internal_email_proto_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_email_proto_email_proto_goTypes = []any{
	(*SendActivationEmailRequest)(nil),  // 0: email.SendActivationEmailRequest
	(*SendActivationEmailResponse)(nil), // 1: email.SendActivationEmailResponse
}
var file_internal_email_proto_email_proto_depIdxs = []int32{
	0, // 0: email.EmailService.SendActivationEmail:input_type -> email.SendActivationEmailRequest
	1, // 1: email.EmailService.SendActivationEmail:output_type -> email.SendActivationEmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_email_proto_email_proto_init() }
func file_internal_email_proto_email_proto_init() {
	if File_internal_email_proto_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_email_proto_email_proto_rawDesc), len(file_internal_email_proto_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_email_proto_email_proto_goTypes,
		DependencyIndexes: file_internal_email_proto_email_proto_depIdxs,
		MessageInfos:      file_internal_email_proto_email_proto_msgTypes,
	}.Build()
	File_internal_email_proto_email_proto = out.File
	file_internal_email_proto_email_proto_goTypes = nil
	file_internal_email_proto_email_proto_depIdxs = nil
}
