// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateAddress = `-- name: CreateOrUpdateAddress :one
INSERT INTO addresses (
  user_id, line1, line2, city, state, postal_code, country
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (user_id) 
DO UPDATE SET 
  line1 = EXCLUDED.line1,
  line2 = EXCLUDED.line2,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  postal_code = EXCLUDED.postal_code,
  country = EXCLUDED.country,
  updated_at = NOW()
RETURNING id, user_id, line1, line2, city, state, postal_code, country, created_at, updated_at
`

type CreateOrUpdateAddressParams struct {
	UserID     int32       `json:"user_id"`
	Line1      string      `json:"line1"`
	Line2      pgtype.Text `json:"line2"`
	City       string      `json:"city"`
	State      string      `json:"state"`
	PostalCode string      `json:"postal_code"`
	Country    string      `json:"country"`
}

func (q *Queries) CreateOrUpdateAddress(ctx context.Context, arg CreateOrUpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createOrUpdateAddress,
		arg.UserID,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressByUserID = `-- name: GetAddressByUserID :one
SELECT id, user_id, line1, line2, city, state, postal_code, country, created_at, updated_at FROM addresses WHERE user_id = $1
`

func (q *Queries) GetAddressByUserID(ctx context.Context, userID int32) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByUserID, userID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
