// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID         int32            `json:"id"`
	UserID     int32            `json:"user_id"`
	Line1      string           `json:"line1"`
	Line2      pgtype.Text      `json:"line2"`
	City       string           `json:"city"`
	State      string           `json:"state"`
	PostalCode string           `json:"postal_code"`
	Country    string           `json:"country"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID               int32              `json:"id"`
	Name             string             `json:"name"`
	Dob              pgtype.Date        `json:"dob"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"password_hash"`
	Role             string             `json:"role"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	IsActive         bool               `json:"is_active"`
	ActivationToken  pgtype.Text        `json:"activation_token"`
	ActivationSentAt pgtype.Timestamptz `json:"activation_sent_at"`
}
