// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrUpdateAddress(ctx context.Context, arg CreateOrUpdateAddressParams) (Address, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int32) error
	GetAddressByUserID(ctx context.Context, userID int32) (Address, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	// UPDATE users
	// SET name = $2, dob = $3
	// WHERE id = $1
	// RETURNING id, name, dob;
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
