// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users
SET is_active = TRUE, activation_token = NULL
WHERE activation_token = $1
RETURNING id, name, dob, email, password_hash, role, created_at, updated_at, is_active, activation_token, activation_sent_at
`

func (q *Queries) ActivateUser(ctx context.Context, activationToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, activateUser, activationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Dob,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.ActivationToken,
		&i.ActivationSentAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, dob, email, password_hash, role, activation_token)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, dob, email, password_hash, role, created_at, updated_at, is_active, activation_token, activation_sent_at
`

type CreateUserParams struct {
	Name            string      `json:"name"`
	Dob             pgtype.Date `json:"dob"`
	Email           string      `json:"email"`
	PasswordHash    string      `json:"password_hash"`
	Role            string      `json:"role"`
	ActivationToken pgtype.Text `json:"activation_token"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Dob,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.ActivationToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Dob,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.ActivationToken,
		&i.ActivationSentAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, dob, email, password_hash, role, created_at, updated_at, is_active, activation_token, activation_sent_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Dob,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.ActivationToken,
		&i.ActivationSentAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, dob, email, password_hash, role, created_at, updated_at, is_active, activation_token, activation_sent_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Dob,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.ActivationToken,
		&i.ActivationSentAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, dob FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID   int32       `json:"id"`
	Name string      `json:"name"`
	Dob  pgtype.Date `json:"dob"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Dob); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one

UPDATE users 
SET 
  -- We use sqlc.arg(name) to force the Go struct field to be "Name"
  name = COALESCE(NULLIF($1, ''), name), 
  
  -- We use sqlc.arg(dob) to force the Go struct field to be "Dob"
  dob = COALESCE($2, dob),
  
  updated_at = NOW()
WHERE id = $3
RETURNING id, name, dob, email, password_hash, role, created_at, updated_at, is_active, activation_token, activation_sent_at
`

type UpdateUserParams struct {
	Name interface{} `json:"name"`
	Dob  pgtype.Date `json:"dob"`
	ID   int32       `json:"id"`
}

// UPDATE users
// SET name = $2, dob = $3
// WHERE id = $1
// RETURNING id, name, dob;
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.Dob, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Dob,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.ActivationToken,
		&i.ActivationSentAt,
	)
	return i, err
}
